import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {randomUUID} from 'node:crypto';
import {createStore} from './store.mjs';
import {createRunStore} from './core/run-store.mjs';
import {buildSearchIndex} from './core/search-index.mjs';
import {hash} from './core/catalog.mjs';
import {createServer} from 'node:net';

test('API serves persisted products/context, activates consistent tenant snapshots, and rejects foreign versions',async()=>{
 const root=await mkdtemp(tmpdir()+'/build-api-');process.env.STUDIO_DATA_DIR=root;
 const probe=createServer().listen(0,'127.0.0.1');await new Promise(r=>probe.once('listening',r));const port=probe.address().port;await new Promise(r=>probe.close(r));process.env.STUDIO_PORT=String(port);
 const {app}=await import('./server.mjs');const server=app.listen(port,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 try{const store=createStore(root),runs=createRunStore(root+'/runs'),id=randomUUID(),runId=randomUUID();
  const profile={name:'Store',domain:'watches',productTypes:{},colors:{},finishes:{},queryAliases:{},tagDefinitions:{},badgeCandidates:{categories:[],tags:[]},badgeRules:[],pipeline:{maxCandidates:20,lightweightRouter:false}};
  const raw={id:'1',name:'Original watch',url:'https://example.com/one',stockStatus:'instock',status:'ACTIVE',price:100,categories:[],tags:[]};
  const card={id:'1',tenantId:id,title:raw.name,url:raw.url,stockStatus:'instock',hidden:false,price:100,categories:[],tags:[],colors:[],finishes:[],badges:[],specifications:{}};
  const bundle={id:runId,projectId:id,profile,catalog:{products:[raw]},productCards:[card],tagAssignments:{},storeContext:{name:'Store'},searchIndex:buildSearchIndex([card],runId)};
  const p={id,url:'https://example.com/',name:'Store',platform:'custom',status:'draft',events:[],messages:[],revisions:[{number:1,profile,note:'build'}],latestBuildId:runId,buildRunId:runId,productCardsProfileHash:hash(profile),...Object.fromEntries(['catalog','productCards','tagAssignments','storeContext','searchIndex'].map(k=>[k,bundle[k]])),updatedAt:new Date().toISOString()};
  await store.save(p);await runs.save({id:runId,projectId:id,status:'ready',createdAt:new Date().toISOString(),validation:{passed:true},stages:[]});await runs.asset(runId,'bundle',bundle);
  const base='http://127.0.0.1:'+server.address().port,headers={Host:'127.0.0.1:'+(process.env.STUDIO_PORT||4320),'Content-Type':'application/json'};
  const {token}=await (await fetch(base+'/api/session',{headers})).json();headers['X-Studio-Token']=token;
  const request=async(path,body)=>{const response=await fetch(base+'/api/projects/'+id+path,{headers,method:body===undefined?'GET':'POST',body:body===undefined?undefined:JSON.stringify(body)});return {status:response.status,data:await response.json()};};
  const result=await request('');assert.equal(result.status,200,JSON.stringify(result.data));const summary=result.data;assert.equal(summary.catalog.count,1);assert.equal(summary.productCards,undefined);assert.equal(summary.buildRun.status,'ready');
  assert.equal((await request('/products')).data.products[0].title,'Original watch');assert.equal((await request('/context')).data.name,'Store');
  assert.equal((await request('/activate',{})).status,200);
  p.catalog.products[0].name='Changed draft';p.updatedAt=new Date(Date.now()+1000).toISOString();p.activeBuildId=runId;await store.save(p);
  const active=await request('/active/search',{query:'1'});assert.equal(active.status,200);assert.equal(active.data.matches[0].title,'Original watch');assert.equal(active.data.matches[0].tenantId,id);
  await runs.save({id:runId,projectId:id,status:'partial',createdAt:new Date().toISOString(),validation:{passed:false},stages:[{key:'index',status:'completed'}]});p.revisions=[];await store.save(p);
  assert.equal((await request('')).data.previewSearchAvailable,true);
  const preview=await request('/search',{query:'1',runId});assert.equal(preview.status,200,JSON.stringify(preview.data));assert.equal(preview.data.matches[0].title,'Original watch');assert.equal(preview.data.metadata.preview,true);
  assert.equal((await request('/activate',{runId})).status,400);
  assert.deepEqual((await store.read(id)).revisions,[]);
  const foreignId=randomUUID();await runs.save({id:foreignId,projectId:randomUUID(),status:'ready',validation:{passed:true}});assert.equal((await request('/activate',{runId:foreignId})).status,400);
  assert.equal((await request('/search',{query:'1',runId:foreignId})).status,400);
  let calls=0;app.locals.chatAgent=async prompt=>{assert.ok(prompt.includes('Execute the operator prompt'));return calls++===0?{tools:[{name:'products',categories:[],nameContains:'watch'}]}:{operations:[{type:'scoped_alias',selectionId:'selection-1',term:'שעון בדיקה'}],testQueries:['שעון בדיקה'],message:'נוסף כינוי ממוקד'};};
  const edited=await request('/chat',{message:'תקן את המודול'});assert.equal(edited.status,200,JSON.stringify(edited.data));assert.equal(edited.data.revisions.length,2);assert.equal(edited.data.revisions.at(-1).profile.scopedAliases[0].term,'שעון בדיקה');assert.equal(edited.data.previewSearchAvailable,false);assert.ok(!edited.data.tagging);
  assert.deepEqual((await store.read(id)).catalog.products,(await runs.asset(runId,'bundle')).catalog.products);
  assert.equal((await request('/search',{query:'1'})).status,200);assert.equal((await runs.read(runId)).status,'partial');
  assert.equal((await request('/activate',{runId})).status,400);
  const current=(await store.read(id)).revisions.at(-1).profile;
  app.locals.chatAgent=async prompt=>{assert.ok(prompt.includes('תוצאות חסרות'));return {operations:[],message:'איזה מוצר ציפית לראות?'}};
  const unchanged=await request('/chat',{message:'לא עובד',context:{label:'תוצאות חסרות',query:'שעון'}});
  assert.equal(unchanged.status,200);assert.equal(unchanged.data.revisions.length,2);assert.deepEqual(unchanged.data.messages.at(-1).changes,[]);
  assert.equal((await request('/chat',{message:'test',context:{label:'x'.repeat(6001)}})).status,400);
  const tagged=await store.read(id),rule={definition:'Source says square',queryAliases:['square']};
  tagged.revisions.at(-1).profile.tagDefinitions={square:rule};tagged.tagAssignments={square:{definitionHash:hash(rule),matchedIds:['1'],decisions:[{productId:'1',status:'matched',quote:'square',definitionHash:hash(rule)}]}};await store.save(tagged);
  const oldIndex=JSON.stringify(tagged.searchIndex),oldCards=JSON.stringify(tagged.productCards);
  app.locals.chatAgent=async()=>({message:'נוסף כינוי לתגית קיימת',operations:[{type:'tag_alias',tag:'square',alias:'מרובע'}],testQueries:[]});
  const tagEdit=await request('/chat',{message:'הוסף כינוי מרובע לתגית square'});assert.equal(tagEdit.status,200,JSON.stringify(tagEdit.data));const saved=await store.read(id);
  assert.ok(!saved.tagging);assert.deepEqual(saved.tagAssignments.square.matchedIds,['1']);assert.equal(saved.tagAssignments.square.definitionHash,hash(saved.revisions.at(-1).profile.tagDefinitions.square));assert.equal(JSON.stringify(saved.searchIndex),oldIndex);assert.equal(JSON.stringify(saved.productCards),oldCards);
  assert.equal((await request('/repair',{stage:'tags',runId})).status,409);
  const imported=await request('/learning',{action:'import'});assert.equal(imported.status,200);const example=imported.data.learning.examples[0];assert.equal(example.status,'pending');
  app.locals.learningAgent=async()=>({suggestions:[{exampleId:example.id,query:'מד זמן לבדיקה',reason:'ניסוח לבדיקה'}]});
  const proposed=await request('/learning',{action:'propose'});assert.equal(proposed.status,200,JSON.stringify(proposed.data));const suggestion=proposed.data.learning.proposals[0];
  assert.equal((await request('/learning',{action:'apply',id:suggestion.id})).status,400);
  assert.equal((await request('/learning',{action:'review',id:example.id,status:'confirmed'})).status,200);
  const applied=await request('/learning',{action:'apply',id:suggestion.id});assert.equal(applied.status,200,JSON.stringify(applied.data));assert.equal(applied.data.learning.proposals[0].status,'applied');
  const afterLearning=await store.read(id);assert.equal(JSON.stringify(afterLearning.searchIndex),oldIndex);assert.equal(JSON.stringify(afterLearning.productCards),oldCards);assert.ok(!afterLearning.tagging);
  app.locals.chatAgent=async()=>({message:'הסר כלל',operations:[{type:'remove_scoped_alias',term:'שעון בדיקה'}],testQueries:[]});
  assert.equal((await request('/chat',{message:'הסר כלל'})).status,400);
  app.locals.workspaceAgent=async()=>({unexpected:'diagnostic-test'});
  const failedAgent=await request('/agent',{message:'בדיקת לוג כישלון'});assert.equal(failedAgent.status,400);
  const logs=await request('/agent-logs');assert.equal(logs.status,200);assert.equal(logs.data.runs[0].status,'failed');assert.ok(logs.data.runs[0].events.some(e=>e.type==='model_response'&&e.raw.includes('diagnostic-test')));assert.ok(logs.data.runs[0].events.some(e=>e.type==='protocol_error'));
  delete app.locals.workspaceAgent;
  delete app.locals.learningAgent;
  delete app.locals.chatAgent;
  assert.equal((await fetch(base+'/api/projects/'+id+'/sync/event',{headers:{Host:headers.Host,'Content-Type':'application/json'},method:'POST',body:'{}'})).status,403);
 }finally{await new Promise(r=>server.close(r));await rm(root,{recursive:true,force:true});}
});
