import {test} from 'node:test';import assert from 'node:assert/strict';
import {createDraftRuntime} from './runtime.mjs';import {hash} from './core/catalog.mjs';
import {learningState,importExamples,reviewExample,guardLearning,proposeLearning,acceptProposal,refreshProposal,evaluateExamples} from './core/learning.mjs';
const profile={name:'Store',domain:'home',productTypes:{},colors:{},finishes:{},queryAliases:{},tagDefinitions:{},badgeCandidates:{categories:[],tags:[]},badgeRules:[],pipeline:{maxCandidates:20,lightweightRouter:false},scopedAliases:[{id:'coffee',term:'כוס קפה',productIds:['1']}]};
function fixture(){const p={id:'t',url:'https://example.com',platform:'custom',messages:[],revisions:[{number:1,profile:structuredClone(profile)}],catalog:{products:[{id:'1',name:'מאג קרמיקה',categories:['כוסות'],tags:[],stockStatus:'instock',status:'ACTIVE'},{id:'2',name:'גביע יין',categories:['כוסות'],tags:[],stockStatus:'instock',status:'ACTIVE'}]}};const rt=createDraftRuntime(p,p.revisions[0]);return {...p,productCards:rt.products,searchIndex:rt.index,productCardsProfileHash:hash(profile)};}
test('import is idempotent and historical/model examples never become confirmed automatically',()=>{const p=fixture();assert.equal(importExamples(p),1);assert.equal(importExamples(p),0);assert.equal(p.learning.examples[0].status,'pending');assert.equal(guardLearning(p,{...profile,scopedAliases:[]}).tested,0);});
test('confirmed positive and negative examples block regressions',()=>{const p=fixture();importExamples(p);reviewExample(p,p.learning.examples[0].id,'confirmed',{excludeIds:['2']});assert.equal(evaluateExamples(p,profile)[0].passed,true);assert.throws(()=>guardLearning(p,{...profile,scopedAliases:[]}),/לא נשמר/);assert.throws(()=>guardLearning(p,{...profile,scopedAliases:[{...profile.scopedAliases[0],productIds:['1','2']}]}),/לא נשמר/);});
test('proposals are bounded, evaluated, and cannot apply without confirmed seeds',async()=>{
 const p=fixture();importExamples(p);const seed=p.learning.examples[0];const oldCards=JSON.stringify(p.productCards),oldIndex=JSON.stringify(p.searchIndex);
 await proposeLearning(p,async()=>({suggestions:[{exampleId:seed.id,query:'ספל קפה',reason:'ניסוח חלופי'}]}));const suggestion=p.learning.proposals[0];assert.equal(suggestion.status,'pending');assert.equal(p.revisions.length,1);assert.throws(()=>acceptProposal(p,suggestion.id),/לאשר/);
 reviewExample(p,seed.id,'confirmed',{excludeIds:['2']});refreshProposal(p,suggestion.id);acceptProposal(p,suggestion.id);assert.equal(p.revisions.length,2);assert.equal(p.learning.examples.length,2);assert.equal(p.learning.examples[1].status,'confirmed');assert.equal(p.learning.proposals[0].status,'applied');assert.equal(JSON.stringify(p.productCards),oldCards);assert.equal(JSON.stringify(p.searchIndex),oldIndex);assert.ok(!p.tagging);
 assert.equal(evaluateExamples(p,p.revisions.at(-1).profile).every(r=>r.passed),true);
});
test('stale proposals require retest; unavailable products never pass',async()=>{const p=fixture();importExamples(p);const seed=p.learning.examples[0];reviewExample(p,seed.id,'confirmed');await proposeLearning(p,async()=>({suggestions:[{exampleId:seed.id,query:'ספל קפה',reason:'ניסוח חלופי'}]}));p.revisions[0].profile.queryAliases.x='y';assert.throws(()=>acceptProposal(p,p.learning.proposals[0].id),/השתנו/);refreshProposal(p,p.learning.proposals[0].id);p.learning.examples[0].includeIds.push('deleted');assert.equal(evaluateExamples(p,p.revisions[0].profile)[0].passed,false);});
test('review rejects foreign or contradictory products and suggestions reject invented seeds',async()=>{const p=fixture();importExamples(p);const id=p.learning.examples[0].id;assert.throws(()=>reviewExample(p,id,'confirmed',{excludeIds:['foreign']}));assert.throws(()=>reviewExample(p,id,'confirmed',{excludeIds:['1']}));await assert.rejects(()=>proposeLearning(p,async()=>({suggestions:[{exampleId:'foreign',query:'q',reason:'r'}]})));});
