import {test} from 'node:test';import assert from 'node:assert/strict';import {workspaceAgent,processField} from './core/workspace-agent.mjs';import {existingProject} from './existing-client.mjs';import {createIndexRetriever} from './core/search-index.mjs';
const fixture=()=>existingProject('books',{dbName:'books'},[{id:'1',name:'Book',specifications:{publisher:'Penguin'},stockStatus:'instock'}]);
test('agent adds searchable derived field atomically, preserves source and can undo',async()=>{const p=fixture();let n=0;const agent=async prompt=>prompt.startsWith('Transform')?{values:[{id:0,text:'פינגווין'}]}:++n===1?{tools:[{name:'process_field',source:'specifications.publisher',target:'publisher_he',instruction:'תעתיק עברי',category:''}]}:{message:'נוסף תעתיק'};const next=await workspaceAgent(p,'הוסף תעתיק',null,agent);assert.equal(p.productCards[0].specifications.publisher_he,undefined);assert.equal(next.productCards[0].specifications.publisher,'Penguin');assert.equal(createIndexRetriever(next.productCards,{...next.revisions[0].profile,tenantId:next.id},next.searchIndex)('פינגווין').total,1);let step=0;const undo=await workspaceAgent(next,'בטל',null,async()=>step++?{message:'בוטל'}:{tools:[{name:'undo_processing'}]});assert.equal(undo.productCards[0].specifications.publisher_he,undefined);});
test('database tools describe, search and import a field into searchable cards',async()=>{
 const {describeFields,dbSearch,importDbField}=await import('./existing-client.mjs');
 const docs=[{_id:'x',id:'1',name:'Book',meta:{illustrator:'Quentin Blake'},awards:[{name:'Carnegie'}]}];
 const fields=describeFields(docs);assert.deepEqual(fields.find(f=>f.field==='meta.illustrator').examples,['Quentin Blake']);assert.equal(fields.find(f=>f.field==='awards').examples[0],'Carnegie');assert.ok(!fields.some(f=>f.field==='_id'));
 await assert.rejects(()=>dbSearch(fixture(),{field:'$where'},()=>assert.fail('must not connect')),/שם שדה/);
 let seen;const open=async(_p,fn)=>fn({find(filter){seen=filter;return docs}});const p=fixture();
 await assert.rejects(()=>importDbField(p,{field:'meta.illustrator',target:'publisher'},open),/כבר קיים/);
 const r=await importDbField(p,{field:'meta.illustrator',target:'illustrator'},open);assert.equal(r.imported,1);assert.deepEqual(seen,{'meta.illustrator':{$exists:true}});assert.equal(p.productCards[0].specifications.illustrator,'Quentin Blake');
 let n=0;const database={fields:async()=>({fields}),search:async(_p,a)=>({total:1,args:a}),importField:(q,a)=>importDbField(q,a,open)};
 const next=await workspaceAgent(fixture(),'הוסף מאייר',null,async()=>++n===1?{tools:[{name:'db_fields'},{name:'db_search',field:'meta.illustrator',contains:'blake'},{name:'db_import_field',field:'meta.illustrator',target:'illustrator'}]}:{message:'נוסף'},{database});
 assert.equal(createIndexRetriever(next.productCards,{...next.revisions[0].profile,tenantId:next.id},next.searchIndex)('Quentin').total,1);
});
test('invalid or hallucinated processing output cannot mutate original cards',async()=>{const p=fixture(),before=JSON.stringify(p);await assert.rejects(()=>workspaceAgent(p,'תרגם',null,async prompt=>prompt.startsWith('Transform')?{values:[{id:999,text:'fake'}]}:{tools:[{name:'process_field',source:'title',target:'title_he',instruction:'translate',category:''}]}));assert.equal(JSON.stringify(p),before);});
test('configuration creates a revision and read-only questions do not',async()=>{const p=fixture();let n=0;const next=await workspaceAgent(p,'הגדל מועמדים',null,async()=>n++?{message:'עודכן'}:{tools:[{name:'configure_search',maxCandidates:80,lightweightRouter:false}]});assert.equal(next.revisions.length,2);assert.equal(p.revisions[0].profile.pipeline.maxCandidates,100);const read=await workspaceAgent(p,'מה יש?',null,async()=>({message:'קטלוג ספרים'}));assert.equal(read.revisions.length,1);});
test('malformed protocol retries once and exposes diagnostic when still invalid',async()=>{const p=fixture(),events=[];let calls=0;const next=await workspaceAgent(p,'בדיקה',null,async()=>++calls===1?{response:'wrong shape'}:{message:'תוקן'},{onEvent:async e=>events.push(e)});assert.equal(calls,2);assert.equal(events[0].type,'protocol_error');assert.equal(next.messages.at(-1).text,'תוקן');await assert.rejects(()=>workspaceAgent(p,'בדיקה',null,async()=>({response:'bad'})),/response/);});
test('accepts the singleton object array returned in the failing production logs',async()=>{const {parseAgentResponse}=await import('./model.mjs');assert.deepEqual(parseAgentResponse('[{"tools":[{"name":"reindex"}]}]'),{tools:[{name:'reindex'}]});assert.throws(()=>parseAgentResponse('[{},{}]'));assert.throws(()=>parseAgentResponse('not JSON'));});
test('tag fields and tag-based scopes work; tool failures are visible and recoverable',async()=>{const p=fixture();p.productCards[0].tags=['ספרים בעברית'];let n=0;const events=[];const next=await workspaceAgent(p,'עבד תגיות',null,async prompt=>prompt.startsWith('Transform')?{values:[{id:0,text:'Hebrew books'}]}:++n===1?{tools:[{name:'process_field',source:'missing',target:'bad',instruction:'translate',category:''}]}:n===2?{tools:[{name:'process_field',source:'tags',target:'tags_en',instruction:'translate',category:'ספרים בעברית'}]}:{message:'השדה תורגם לאחר תיקון הכלי'},{onEvent:async e=>events.push(e)});assert.equal(next.productCards[0].specifications.tags_en,'Hebrew books');assert.ok(events.some(e=>e.type==='tool_error'));assert.equal(p.productCards[0].specifications.tags_en,undefined);});
test('a key missing its opening quote is repaired locally, and a list of replies reaches the merge',async()=>{
 const {parseAgentResponse,mergeReplies}=await import('./model.mjs');
 assert.deepEqual(parseAgentResponse('{"tools":[{"name":"list_rules"},{name":"search","query":"פסטה"}]}'),{tools:[{name:'list_rules'},{name:'search',query:'פסטה'}]});
 // Garmin, plugin question: arguments sent as a bare object after the tool name.
 assert.deepEqual(parseAgentResponse('{"note":"x","tools":[{"name":"plugin_files",{}}]}'),{note:'x',tools:[{name:'plugin_files'}]});
 assert.deepEqual(parseAgentResponse('{"tools":[{"name":"plugin_read",{"path":"a.js","offset":0}}]}'),{tools:[{name:'plugin_read',path:'a.js',offset:0}]});
 assert.deepEqual(mergeReplies(parseAgentResponse('[{"note":"a","tools":[{"name":"x"}]},{"tools":[{"name":"y"}]}]')),{note:'a',tools:[{name:'x'},{name:'y'}]});
 assert.throws(()=>parseAgentResponse('{"tools":[oops]}'));
});
